services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /docker/radarr/config:/config
      - /drives/atlantis:/movies
      - /drives/downloaddrive:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
