services:
  arcane-edge-agent:
    image: ghcr.io/getarcaneapp/arcane-headless:latest
    container_name: arcane-edge-agent
    restart: unless-stopped
    env_file: /docker/arcane/.env
    environment:
      - EDGE_AGENT=true
      - EDGE_TRANSPORT=poll
      - MANAGER_API_URL=http://192.168.2.201:3552
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/arcane/arcane-data:/app/data
volumes:
  arcane-data: