services:
  huntarr:
    image: ghcr.io/plexguide/huntarr:latest
    container_name: huntarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - PORT=8686 # Default is often 8686
    volumes:
      - /docker/huntarr/config:/config
    ports:
      - "8686:8686"
    restart: unless-stopped