services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - PORT=7878
    volumes:
      - /docker/radarr/config:/config
      - /drives/alfheim/movies:/movies
      - /drives/theseed/downloads/complete:/downloads/complete
    ports:
      - "7878:7878"
    restart: unless-stopped
