services:
  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - PORT=8990 # Need to differentiatie all the ports and then name the instance in the settings under general > advanced > hostname
    volumes:
      - /docker/sonarr-anime/config:/config # Separate config for separate instance
      - /drives/aincrad/anime-shows:/anime-shows
      - /drives/theseed/downloads/complete:/downloads/complete
    ports:
      - "8990:8990"
    restart: unless-stopped
